CREATE TABLE `products`(
	`Id` INT(10) AUTO_INCREMENT PRIMARY KEY,
	`ProductName` VARCHAR(50) NULL DEFAULT NULL,	
	`Description` VARCHAR(50) NULL DEFAULT NULL, 
	`Image` VARCHAR(50) NULL DEFAULT NULL,
	`Price` INT(20) NULL DEFAULT NULL,
	`Quantity` INT(20) NULL DEFAULT NULL,
	`store_id` INT(10) NULL DEFAULT NULL
)ENGINE=InnoDB;